Martian Runtime - v4.0.1-35-gaac608b-dirty
2020-10-09 19:11:03 [build  ] Built with Go version go1.15.2
2020-10-09 19:11:03 [cmdline] mrp --autoretry=3 --vdrmode=strict pipeline.mro pipeline_test
2020-10-09 19:11:03 [pid    ] 1622551
2020-10-09 19:11:03 [environ] HOSTNAME=localhost
2020-10-09 19:11:03 [environ] TERM=xterm-256color
2020-10-09 19:11:03 [environ] SHELL=/bin/bash
2020-10-09 19:11:03 [environ] USER=mario
2020-10-09 19:11:03 [environ] PATH=../../bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/local/sbin:/usr/sbin
2020-10-09 19:11:03 [environ] PWD=/user/test/retry_test
2020-10-09 19:11:03 [environ] LANG=en_US.UTF-8
2020-10-09 19:11:03 [environ] SHLVL=6
2020-10-09 19:11:03 [environ] HOME=/user/mario
2020-10-09 19:11:03 [environ] LOGNAME=mario
2020-10-09 19:11:03 [environ] _=../../bin/mrp
2020-10-09 19:11:03 [environ] MROFLAGS=--disablei
2020-10-09 19:11:03 [environ] MROPATH=/user/test/retry_test
2020-10-09 19:11:03 [version] MRO Version=v4.0.1-35-gaac608b
2020-10-09 19:11:03 [options] --jobmode=local
2020-10-09 19:11:03 [options] --vdrmode=strict
2020-10-09 19:11:03 [options] --profile=disable
2020-10-09 19:11:03 [options] --disablei
2020-10-09 19:11:03 [options] --stackvars=false
2020-10-09 19:11:03 [options] --zip=false
2020-10-09 19:11:03 [options] --limit-loadavg=false
2020-10-09 19:11:03 [options] --noexit=false
2020-10-09 19:11:03 [options] --nopreflight=false
2020-10-09 19:11:03 [options] --autoretry=3
2020-10-09 19:11:03 [jobmngr] Job config = /user/jobmanagers/config.json
2020-10-09 19:11:03 [jobmngr] Using XX logical cores available on system.
2020-10-09 19:11:03 [jobmngr] Using XX GB, 90% of system memory.
2020-10-09 19:11:04 [sysinfo] linux amd64
2020-10-09 19:11:04 [sysinfo] Linux kernel release version: 5.4.20-12.75.amzn2.x86_64
2020-10-09 19:11:04 [sysinfo] glibc version: 2.26
2020-10-09 19:11:04 [filesys] Pipestance path /user/test/retry_test/pipeline_test
2020-10-09 19:11:04 [filesys] Pipestance filesystem type nfs
2020-10-09 19:11:04 [filesys] 2.3 TB and 192,124,143 inodes available.
2020-10-09 19:11:04 [filesys] Pipestance filesystem nfs mount options: rw,nosuid,relatime,rw,vers=3,rsize=65536,wsize=65536,namlen=255,hard
2020-10-09 19:11:04 [filesys] Bin path /user/bin
2020-10-09 19:11:04 [filesys] Bin filesystem type nfs
2020-10-09 19:11:04 [filesys] Bin filesystem nfs mount options: rw,nosuid,relatime,rw,vers=3,rsize=65536,wsize=65536,namlen=255,hard
2020-10-09 19:11:04 [webserv] UI disabled.
Running preflight checks (please wait)...
2020-10-09 19:11:04 [jobmngr] 18.8GB less memory than expected was free
2020-10-09 19:11:04 [jobmngr] cgroup rss usage is 82.6GB, vs. limit of 8589934592.0
2020-10-09 19:11:04 [runtime] (ready)           ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:04 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.split
2020-10-09 19:11:04 [runtime] (split_complete)  ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:04 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.chnk0.main
2020-10-09 19:11:05 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.chnk1.main
2020-10-09 19:11:05 [runtime] (failed)          ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:05 [runtime] Waiting 1s before attempting a retry.
2020-10-09 19:11:06 [runtime] Transient error detected.  Log content:

Traceback (most recent call last):
  File "/user/adapters/python/martian_shell.py", line 659, in _main
    stage.main()
  File "/user/adapters/python/martian_shell.py", line 618, in main
    self._run(lambda: self._module.main(args, outs))
  File "/user/adapters/python/martian_shell.py", line 589, in _run
    cmd()
  File "/user/adapters/python/martian_shell.py", line 618, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/user/test/retry_test/stage/__init__.py", line 73, in main
    martian.throw("resource temporarily unavailable")
  File "/user/adapters/python/martian.py", line 299, in throw
    raise StageException(message)
StageException: resource temporarily unavailable


2020-10-09 19:11:06 [runtime] Attempting retry.
2020-10-09 19:11:06 [runtime] Reattaching in local mode.
2020-10-09 19:11:06 [runtime] (reset-partial)   ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.chnk0
2020-10-09 19:11:09 [runtime] (split_complete)  ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:09 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.chnk0.main
2020-10-09 19:11:10 [runtime] (chunks_complete) ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:10 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.BEGIN.fork0.join
2020-10-09 19:11:10 [runtime] (join_complete)   ID.pipeline_test.SHOULD_RESTART.BEGIN
2020-10-09 19:11:10 [runtime] Adding 1 new forks of ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:11 [runtime] (ready)           ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:11 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0.chnk0.main
2020-10-09 19:11:11 [runtime] (ready)           ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork1
2020-10-09 19:11:11 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork1.chnk0.main
2020-10-09 19:11:11 [runtime] (failed)          ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:11 [runtime] Waiting 1s before attempting a retry.
2020-10-09 19:11:12 [runtime] Transient error detected.  Log content:

Traceback (most recent call last):
  File "/user/adapters/python/martian_shell.py", line 659, in _main
    stage.main()
  File "/user/adapters/python/martian_shell.py", line 618, in main
    self._run(lambda: self._module.main(args, outs))
  File "/user/adapters/python/martian_shell.py", line 589, in _run
    cmd()
  File "/user/adapters/python/martian_shell.py", line 618, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/user/test/retry_test/stage/__init__.py", line 73, in main
    martian.throw("resource temporarily unavailable")
  File "/user/adapters/python/martian.py", line 299, in throw
    raise StageException(message)
StageException: resource temporarily unavailable


2020-10-09 19:11:12 [runtime] Attempting retry.
2020-10-09 19:11:12 [runtime] Reattaching in local mode.
2020-10-09 19:11:12 [runtime] Adding 1 new forks of ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:12 [runtime] Adding 1 new forks of ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:13 [runtime] (reset-partial)   ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0.chnk0
2020-10-09 19:11:13 [runtime] (split_complete)  ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:13 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0.chnk0.main
2020-10-09 19:11:13 [runtime] (chunks_complete) ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork1
2020-10-09 19:11:13 [runtime] (chunks_complete) ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:13 [runtime] (complete)        ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork1
2020-10-09 19:11:13 [runtime] (ready)           ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:14 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.END.fork0.chnk0.main
2020-10-09 19:11:14 [runtime] (ready)           ID.pipeline_test.SHOULD_RESTART.END.fork1
2020-10-09 19:11:14 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.END.fork1.chnk0.main
2020-10-09 19:11:14 [runtime] (failed)          ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:14 [runtime] Waiting 1s before attempting a retry.
2020-10-09 19:11:15 [runtime] Transient error detected.  Log content:

Traceback (most recent call last):
  File "/user/adapters/python/martian_shell.py", line 659, in _main
    stage.main()
  File "/user/adapters/python/martian_shell.py", line 618, in main
    self._run(lambda: self._module.main(args, outs))
  File "/user/adapters/python/martian_shell.py", line 589, in _run
    cmd()
  File "/user/adapters/python/martian_shell.py", line 618, in <lambda>
    self._run(lambda: self._module.main(args, outs))
  File "/user/test/retry_test/stage/__init__.py", line 73, in main
    martian.throw("resource temporarily unavailable")
  File "/user/adapters/python/martian.py", line 299, in throw
    raise StageException(message)
StageException: resource temporarily unavailable


2020-10-09 19:11:15 [runtime] Attempting retry.
2020-10-09 19:11:15 [runtime] Reattaching in local mode.
2020-10-09 19:11:15 [runtime] Adding 1 new forks of ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:15 [runtime] Adding 1 new forks of ID.pipeline_test.SHOULD_RESTART.MIDDLE.fork0
2020-10-09 19:11:15 [runtime] (reset-partial)   ID.pipeline_test.SHOULD_RESTART.END.fork0.chnk0
2020-10-09 19:11:16 [runtime] (split_complete)  ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:16 [runtime] (run:local)       ID.pipeline_test.SHOULD_RESTART.END.fork0.chnk0.main
2020-10-09 19:11:16 [runtime] (chunks_complete) ID.pipeline_test.SHOULD_RESTART.END.fork1
2020-10-09 19:11:16 [runtime] (chunks_complete) ID.pipeline_test.SHOULD_RESTART.END.fork0
2020-10-09 19:11:16 [runtime] (complete)        ID.pipeline_test.SHOULD_RESTART.END.fork1
2020-10-09 19:11:17 [runtime] VDR killed 0 files, 0 B.

Outputs:
- sentinels: [
    0: /user/test/retry_test/pipeline_test/outs/sentinels/0
    1: null
  ]

2020-10-09 19:11:17 [perform] Serializing pipestance performance data.
Pipestance completed successfully!

2020-10-09 19:11:17 Shutting down.
2020-10-09 19:11:17 [jobmngr] Highest memory usage observed: {
  "rss": 18313216,
  "shared": 10866688,
  "vmem": 1470529536,
  "text": 9932800,
  "stack": 172056576,
  "proc_count": 24
}
